### ISSUE TITLE
Batch size, resuming from checkpoints and other utilities

### ISSUE THREAD

**Issue by mohitsharma29** [mailong25/self-supervised-speech-recognition#11]
Hey

I was browsing through this code and wanted to know a few things:
1. How can I control the batch size? (Large models will require me to train on very small batch sizes due to limited compute)
2. How can I resume from a checkpoint, currently there is no utility or function in your codebase?

**Comment by mailong25** [comment]
1. I added the batch_size option in the pretrain.py and finetune.py scripts.
2. For pre-training, you can resume checkpoint via `--init_model your_checkpoint`
For fine-tuning, you can resume checkpoint via`--restore_file your_checkpoint`

You can add more config yourself by looking at:
https://github.com/pytorch/fairseq/blob/master/examples/wav2vec/README.md
And:
https://fairseq.readthedocs.io/en/latest/command_line_tools.html
