### ISSUE TITLE
Validation in finetune.py and Tensorboarding

### ISSUE THREAD

**Issue by mohitsharma29** [mailong25/self-supervised-speech-recognition#12]
Hey

Once again, thanks for making a nice wrapper. I understand that your code ultimately calls the wav2vec commands given in the original repository. I have some questions which didn't get resolved there and I would love your suggestions:

1. Like in pretrain.py, because you call manifest.py, you are able to set some part for validation. However, how do you think one can supply a validation split in finetune.py?
2. How do I create a nice tensorboard log on the existing hydra logs? Any existing utilities that can help me do it?

Thanks for helping out.

**Comment by mailong25** [comment]
I added `valid_percent` arg for #1.
For #2, for both pretrain and finetune:
You can add: `cmd.append("common.tensorboard_logdir=log_dir_name/"` just before the line `cmd.append("--config-dir config/finetuning")` and `cmd.append("--config-dir config/pretraining")`
