### ISSUE TITLE
Loading Audio array directly into transcribe, instead of supplying Audio Path

### ISSUE THREAD

**Issue by mohitsharma29** [mailong25/self-supervised-speech-recognition#13]
Hey

Right now, the transcribe function expects audio paths. What if we want to supply a NumPy array of audios preloaded? Can we modify this in stt.py or does fairseq/wav2vec demand audio paths?

Once again, thanks for your quick responses.

**Comment by mailong25** [comment]
The wav2vec's code take audio paths, convert them into a dataset and then make predictions. You can modify this in stt.py, the is taken from original wav2vec repo:
https://github.com/pytorch/fairseq/blob/master/examples/speech_recognition/infer.py
