### ISSUE TITLE
malloc(): mismatching next->prev_size (unsorted)

### ISSUE THREAD

**Issue by kjellvb** [mailong25/self-supervised-speech-recognition#14]
Hello thank you for this. Everything works fine with me, until the last step when trying to transcribe a file. 
I get the notification: malloc(): mismatching next->prev_size (unsorted), aborted. 
I also sometimes get: segmentation fault, but without any traceback..
Do you know what the cause of this might be?
Thanks :-)

**Comment by mailong25** [comment]
Did the errors occur in every single prediction ?
Did the errors occur when you try to predict a single file or multiple files at the same time ?
You could try to download the Vietnamese model (https://drive.google.com/file/d/1kZFdvMQt-R7fVebTbfWMk8Op7I9d24so/view?usp=sharing), use it to make predictions on your own data to see what happen.

**Comment by kjellvb** [comment]
Yes it did occur during every prediction, I also had this error previously when trying to train model without your repo, I thought your code might solve my issues. I tried to make a prediction with your Vietnamese models, and I get exactly the same error. So I suppose the problem is caused by a bad install of wav2letter or something, perhaps should start with clean installs of everything. I already had quite some issues with wav2letter. Thanks for your reply :-)

**Comment by mailong25** [comment]
I dont know much about the "malloc(): mismatching next->prev_size (unsorted)" problem, 
but for the segmentation fault error. I fix it by reinstall the KenLM library as follow:
```
git clone https://github.com/kpu/kenlm.git
cd kenlm
mkdir -p build && cd build
cmake ..
make -j 4
cd ../..
```
Hope this help

**Comment by kjellvb** [comment]
I reinstalled everything and it works now, thank you sooo much !
