### ISSUE TITLE
Hard coding parameters and avoiding argparse

### ISSUE THREAD

**Issue by mohitsharma29** [mailong25/self-supervised-speech-recognition#17]
Hey

I was wondering if you have any suggestions on how to get around argparse for wav2vec? Argparse is great for training, but once you have a set of parameters fixed, argparse must be avoided since it also interferes with other things once the model is part of an application.

I know wav2vec itself uses argparse everywhere, but I was wondering if you might have thought of this problem and a workaround. Thanks.

**Comment by mailong25** [comment]
I used to think about that, but honestly, I am not quite familiar with the design of wav2vec's source.
