### ISSUE TITLE
Segmentation fault in inference

### ISSUE THREAD

**Issue by kingsword5566** [mailong25/self-supervised-speech-recognition#22]
Hi mailong
I follow your install instruction and now stuck at stage 4 (Make prediction on multiple audios programmatically)
It only shows `Segmentation fault (core dumped)`
Is that means my wav2letter installation broken?

**Comment by mailong25** [comment]
Try to reinstall kenlm and wav2letter (from the step 4)
https://github.com/mailong25/self-supervised-speech-recognition/blob/master/Dependencies.md

**Comment by kingsword5566** [comment]
Hi
Reinstalling is not work.

**Comment by kingsword5566** [comment]
Solved!
I add `-DKENLM_MAX_ORDER=20` into `wav2letter/bindings/python/setup.py`
ref: https://github.com/facebookresearch/wav2letter/issues/405
