### ISSUE TITLE
sh: 1: fairseq-hydra-train: not found

### ISSUE THREAD

**Issue by askinucuncu** [mailong25/self-supervised-speech-recognition#23]
When I run pretrain.py or finetune.py I get the following error. 

python pretrain.py --fairseq_path libs/fairseq --audio_path wav --init_model wav2vec_small.pt
fairseq-hydra-train task.data=/home/bcode/speech-recognition/temp distributed_training.distributed_world_size=1 +optimization.update_freq='[64]' checkpoint.finetune_from_model=/home/bcode/speech-recognition/wav2vec_small.pt dataset.num_workers=8 dataset.max_tokens=1200000 --config-dir config/pretraining --config-name wav2vec2_base_librispeech
sh: 1: fairseq-hydra-train: not found

python finetune.py --transcript_file transcript.txt --pretrain_model wav2vec_small.pt --dict_file dict.ltr.txt

100%|████████████████████████████████████| 1831/1831 [00:00<00:00, 15427.24it/s]
fairseq-hydra-train task.data=/home/bcode/speech-recognition/manifest distributed_training.distributed_world_size=1 +optimization.update_freq='[24]' model.w2v_path=/home/bcode/speech-recognition/wav2vec_small.pt dataset.num_workers=8 dataset.max_tokens=2800000 --config-dir config/finetuning --config-name base_1h
sh: 1: fairseq-hydra-train: not found

**Comment by mailong25** [comment]
Are you install the right fairseq version ?
![image](https://user-images.githubusercontent.com/12481660/106829071-fc23f880-66bd-11eb-8a13-34b312d6d022.png)

**Comment by askinucuncu** [comment]
I installed the correct version yes. As described in the document. Strangely, it worked when I restarted the system.
