### ISSUE TITLE
Decoder using build/Decode will reload model?

### ISSUE THREAD

**Issue by phamvandan** [mailong25/self-supervised-speech-recognition#3]
Chào a Mai Long, em thấy phần inference nếu mình đang làm như thế thì đang bị load lại model ạ. Không biết, a đã tinh chỉnh phần inference chưa ạ .

**Comment by mailong25** [comment]
Anh đang dùng off-the-shelf decoder, nên mình sẽ load lại AM model mỗi lần inference. 
E tham khảo thread này để xem có cách nào load model 1 lần thôi không nhé
https://github.com/facebookresearch/wav2letter/issues/537

**Comment by phamvandan** [comment]
Em có đọc của facebook thì người ta có cung cấp streaming inference a ạ. Tuy nhiên, hiện tại nó đang support mỗi kiến trúc mạng stream convnet. Trong code decoder của nó có đoạn create_dataset() và inference, nếu mình chỉnh sửa đoạn này thì có khả thi không a nhỉ.
