### ISSUE TITLE
I am getting an error when installing to Colab

### ISSUE THREAD

**Issue by askinucuncu** [mailong25/self-supervised-speech-recognition#37]
Cloning into 'wav2letter'...
remote: Enumerating objects: 119, done.
remote: Counting objects: 100% (119/119), done.
remote: Compressing objects: 100% (95/95), done.
remote: Total 6587 (delta 34), reused 72 (delta 19), pack-reused 6468
Receiving objects: 100% (6587/6587), 6.13 MiB | 22.26 MiB/s, done.
Resolving deltas: 100% (4207/4207), done.
/content/self-supervised-speech-recognition/libs/wav2letter/bindings/python
env: KENLM_ROOT_DIR=/content/self-supervised-speech-recognition/libs/kenlm
Obtaining file:///content/self-supervised-speech-recognition/libs/wav2letter/bindings/python
Installing collected packages: wav2letter
  Running setup.py develop for wav2letter
ERROR: Command errored out with exit status 1: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/content/self-supervised-speech-recognition/libs/wav2letter/bindings/python/setup.py'"'"'; __file__='"'"'/content/self-supervised-speech-recognition/libs/wav2letter/bindings/python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
/content/self-supervised-speech-recognition/libs

**Comment by bsshruthi22** [comment]
I am also getting the same issue.Please let us know

**Comment by pesipasi** [comment]
I had this problem. In my case, it was because of  kenlm path. In colab, the following command should be used instead of `export path`:
`os.environ['KENLM_ROOT_DIR'] =  "/content/self-supervised-speech-recognition/libs/kenlm"`

**Comment by askinucuncu** [comment]
Colab uses the Cuda 11 version. By following the steps below, we downgrade to Cuda 10.1 first. Then when I installed wav2letter it worked for me.

#Download CUDA 10.1
!wget  --no-clobber https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-10-1_10.1.243-1_amd64.deb
#install CUDA kit dpkg
!dpkg -i cuda-10-1_10.1.243-1_amd64.deb
!sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub
!apt-get update
!apt-get install cuda-10-1

Note: If apt install fails, run the following command.
!sudo apt --fix-broken install
