### ISSUE TITLE
STT problem

### ISSUE THREAD

**Issue by avpodtikhov** [mailong25/self-supervised-speech-recognition#38]
**When creating an instance of Transcriber class, getting the following error:**

usage: data [-h] [--no-progress-bar] [--log-interval LOG_INTERVAL]
            [--log-format {json,none,simple,tqdm}]
            [--tensorboard-logdir TENSORBOARD_LOGDIR] [--seed SEED] [--cpu]
            [--tpu] [--bf16] [--memory-efficient-bf16] [--fp16]
            [--memory-efficient-fp16] [--fp16-no-flatten-grads]
            [etc]
            data
data: error: the following arguments are required: data
An exception has occurred, use %tb to see the full traceback.

**%tb output:**
---------------------------------------------------------------------------
SystemExit                                Traceback (most recent call last)
<ipython-input-18-b0f84205a610> in <module>()
----> 1 parser.parse_args()

4 frames
/usr/lib/python3.7/argparse.py in parse_args(self, args, namespace)
   1762     # =====================================
   1763     def parse_args(self, args=None, namespace=None):
-> 1764         args, argv = self.parse_known_args(args, namespace)
   1765         if argv:
   1766             msg = _('unrecognized arguments: %s')

/usr/lib/python3.7/argparse.py in parse_known_args(self, args, namespace)
   1794         # parse the arguments and exit if there are any errors
   1795         try:
-> 1796             namespace, args = self._parse_known_args(args, namespace)
   1797             if hasattr(namespace, _UNRECOGNIZED_ARGS_ATTR):
   1798                 args.extend(getattr(namespace, _UNRECOGNIZED_ARGS_ATTR))

/usr/lib/python3.7/argparse.py in _parse_known_args(self, arg_strings, namespace)
   2029         if required_actions:
   2030             self.error(_('the following arguments are required: %s') %
-> 2031                        ', '.join(required_actions))
   2032 
   2033         # make sure all required groups had one option present

/usr/lib/python3.7/argparse.py in error(self, message)
   2515         self.print_usage(_sys.stderr)
   2516         args = {'prog': self.prog, 'message': message}
-> 2517         self.exit(2, _('%(prog)s: error: %(message)s\n') % args)

/usr/lib/python3.7/argparse.py in exit(self, status, message)
   2502         if message:
   2503             self._print_message(message, _sys.stderr)
-> 2504         _sys.exit(status)
   2505 
   2506     def error(self, message):

SystemExit: 2

**Comment by martinhoang11** [comment]
Hi, i got the same problem. How did you fix it ?
