### ISSUE TITLE
ValueError in making prediction

### ISSUE THREAD

**Issue by TinBarbie** [mailong25/self-supervised-speech-recognition#43]
Hi, your work is really awesome. I currenly got a ValueError when running prediction by your public Pre-trained models. 
Here is the issue code:
![image](https://user-images.githubusercontent.com/65520145/111939010-c74cf300-8afd-11eb-9ddf-929c7881253d.png)
While i was trying to debug the error via https://github.com/pytorch/fairseq/issues/2106, the problem still occured.
Please tell me how to fix it. My computer os is Windows 10 by the way. Many thanks

**Comment by Aaryan369** [comment]
Hey, were you able to resolve this error? If yes then how?
Thanks.
