### ISSUE TITLE
Can not load checkpoints in the finetuning step

### ISSUE THREAD

**Issue by CSLujunyu** [mailong25/self-supervised-speech-recognition#44]
When I try steps 2.3 (Run Fine-tuning on the pretrained model) and input the proper pretrained model from step 1.3, I got the message below. Is it correct?
![loading_error](https://user-images.githubusercontent.com/24778852/112277692-f6f62980-8cbc-11eb-9340-a68f54b35cfa.png)

**Comment by mailong25** [comment]
Try to use the absolute path

**Comment by CSLujunyu** [comment]
> Try to use the absolute path

I use the absolute path as below.
`fairseq-hydra-train task.data=/data/app/user_data/jacoblu/wav2vec2/finetuning/manifest distributed_training.distributed_world_size=1 +optimization.update_freq='[24]' model.w2v_path=/data/app/user_data/jacoblu/wav2vec2/finetuning/checkpoints/checkpoint_last.pt dataset.num_workers=8 dataset.batch_size=12 --config-dir ../config/finetuning --config-name base_960h`

What's more, I do not input the parameter "restore_file" as you describe at step 2.3(Run Fine-tuning on the pretrain model).

![code](https://user-images.githubusercontent.com/24778852/112315070-b27e8400-8ce4-11eb-92d3-710ec6bc12d7.png)

**Comment by mailong25** [comment]
The "restore_file" is for continue fine-tuning. Let say you fine-tune the model for 10 epoch, then you stop, and now you resume the fine-tuning from epoch 10.

**Comment by mailong25** [comment]
Everything looks fine. You got the "not found" message because you didn't use the "restore_file" param
