### ISSUE TITLE
Any alternative way of installing apt-get packages?

### ISSUE THREAD

**Issue by 18445864529** [mailong25/self-supervised-speech-recognition#60]
Hi, I'm using a server where I don't have sudo permission to install or uninstall packages. So I have trouble following this instruction. Is there any alternative way to solve the dependency in my case?
```
sudo apt-get update && sudo apt-get -y install apt-utils libpq-dev libsndfile-dev
sudo apt install libboost-system-dev libboost-thread-dev libboost-program-options-dev libboost-test-dev libeigen3-dev zlib1g-dev libbz2-dev liblzma-dev
sudo apt-get install libsndfile1-dev libopenblas-dev libfftw3-dev libgflags-dev libgoogle-glog-dev
```
I know this should be a wav2letter related issue or rather an issue of my own side. But I still hope you may offer me some advice on how to alternatively solve this dependency. Thank you very much!

**Comment by tensorfoo** [comment]
Hi, you can try using conda / miniconda. won't need root. i did this for a machine i didn't have access, see how you.
