### ISSUE TITLE
How to calculate WER in testing 

### ISSUE THREAD

**Issue by ThanhBarTN** [mailong25/self-supervised-speech-recognition#8]
Chào anh @mailong25 ,
Em có thử test với một vài file audio có sẵn trong repo này của anh, theo như anh công bố thì WER chỉ tầm 15%, nhưng em test thì WER lại lên đến giá trị 450, mặc dù transcribe đúng ko sai một từ nào, có 1 file transcribe xong sai có 1/11 từ thôi nhưng WER lại lên đến 470, không biết là có nhầm lẫn gì ở đây không ạ 
![image](https://user-images.githubusercontent.com/36233920/100081429-96272380-2e79-11eb-84ca-e76d3304deb0.png)

**Comment by mailong25** [comment]
it's might be a bug in the code.
Anw, you can always use an external software to calculate the WER. Eg https://github.com/jitsi/jiwer

**Comment by ThanhBarTN** [comment]
> it's might be a bug in the code.
> Anw, you can always use an external software to calculate the WER. Eg https://github.com/jitsi/jiwer

Em cảm ơn anh ạ, nếu có gì vướng mắc em xin phép hỏi anh sau ạ
