### ISSUE TITLE
How to create the lexicon.txt

### ISSUE THREAD

**Issue by csikasote** [mailong25/self-supervised-speech-recognition#9]
Hi @mailong25, I am sorry if this is a basic question. I would like to get pointers on how you generated the lexicon.txt. I have an asr dataset (audio + transcriptions)[https://github.com/csikasote/bemba-language-corpus]. My goal is to develop an ASR using wav2vec and wav2letter, possibly adapt your code to my dataset. Did you generate the lexicon.txt from the transcriptions? I would appreciate your help.

**Comment by mailong25** [comment]
Yes, you can use transcription to create the lexicon.txt. 
Make sure that all words present in the transcriptions appear in lexicon.txt file.
You can refer as:
https://github.com/mailong25/wav2letter/blob/master/docs/data_prep.md
